# Generated by Django 2.1.5 on 2019-02-11 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190211_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
