# Generated by Django 2.1.5 on 2019-02-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190211_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
